


/*** 
 * `quotes` array 
***/
var quotes = [
  
  {quote:"¡Ánimo!. Todo pasa. Ama tu trabajo y no dejes de cumplir tu deber cada día. (Don Bosco)", source: "ConfiguroWeb"},
  
{quote:"¿dices que nada se crea? no te importe, con el barro de la tierra, haz una copa para que beba tu hermano. (Antonio Machado)", source: "ConfiguroWeb"},
{quote:"¿Esperar qué? si todo está en usted. (Enrique Aguda)", source: "ConfiguroWeb"},
{quote:"¿Por que contentarnos con vivir a rastras cuando sentimos el anhelo de volar?. (Hellen Keller )", source: "ConfiguroWeb"},
{quote:"A falta de objetivos claros, siendo extremadamente fieles a realizar las trivialidades diarias, nos convertimos en esclavos de ellas. (Robert Heinlein)", source: "ConfiguroWeb"},
{quote:"A menudo, usamos nuestra vista como instrumento, rara vez la disfrutamos. (M. Drury)", source: "ConfiguroWeb"},
{quote:"A muchos sólo les motiva el dinero para ser honesto. (Carlo Dossi. (1849-1910), escritor italiano)", source: "ConfiguroWeb"},
{quote:"A quien no sabe a que puerto encaminarse, ningún viento le es propicio. (Séneca)", source: "ConfiguroWeb"},
{quote:"A un ser humano se le puede quitar todo en la vida, menos su conocimiento, sus pensamientos y sus sueños, que son ideas positivas cargadas de ilusión y de esperanza. (Linares)", source: "ConfiguroWeb"},
{quote:"Abusa del inocente y crea un monstruo. (Jaime Tenorio Valenzuela)", source: "ConfiguroWeb"},
{quote:"Actua como si fueras a realizar tu última acción, mas no dejes nada por temor. (Anael)", source: "ConfiguroWeb"},
{quote:"Al comprenderme a mí misma quiero comprender a los demás. Quiero realizar todo lo que soy capaz de hacer. (Katherine Mansfield)", source: "ConfiguroWeb"},
{quote:"Al parecer, el éxito es una cuestión de perseverar cuando los demás ya han renunciado. (William Feather)", source: "ConfiguroWeb"},
{quote:"Alto profundo es esto que nos une, esto que nos devora y que nos crea; ya se puede vivir teniendo el alma cogida por el alma del que esperas. (Gloria Fuertes)", source: "ConfiguroWeb"},
{quote:"América no es tanto una tradición que continuar como un futuro que realizar. (Octavio Paz)", source: "ConfiguroWeb"},
{quote:"Amigo. Palabra sencilla de exponer pero complicada para realizar. (Pedro Pantoja Santiago)", source: "ConfiguroWeb"},
{quote:"Aquel que lleva en el corazón una visión maravillosa, un ideal noble, algún día lo realizará. (James Allen)", source: "ConfiguroWeb"},
{quote:"Aquel que se ha conquistado a si mismo ha conquistado el universo. (James Allen)", source: "ConfiguroWeb"},
{quote:"Aquello que habita en el pasado y aquello que habita en el futuro, es solo una pequeña cosa, comparado con aquello que habita dentro de nosotros. (Ralph Waldo Emerson)", source: "ConfiguroWeb"},
{quote:"Aquellos que dicen que algo no puede hacerse, suelen ser interrumpidos por otros que lo están haciendo. (Joel A. Barker)", source: "ConfiguroWeb"},
{quote:"Aunque nadie puede volver atrás y lograr un nuevo comienzo, cualquiera puede empezar ahora y lograr un nuevo final. (Roberto Pérez)", source: "ConfiguroWeb"},
{quote:"Aveces el no ser bueno con los demas, da como recompensa ser bueno con uno mismo. (Salvador Fernandez Tavarelli)", source: "ConfiguroWeb"},
{quote:"Cada adversidad, cada fracaso, cada dolor de cabeza, lleva consigo la semilla de un beneficio igual o similar. (Nicholas Murray Butler)", source: "ConfiguroWeb"},
{quote:"Cada ceremonia o rito tiene valor si se realiza sin alteración. Una ceremonia es un libro en el que una gran parte está escrito. Cualquiera entiende que puede leerlo. Un rito a menudo contiene más de un centenar de libros. (George Gurdjieff)", source: "ConfiguroWeb"},
{quote:"Cada día en todos los sentidos estoy mejor, mejor y mejor. (Emile Coué)", source: "ConfiguroWeb"},
{quote:"Cada persona es tan feliz como se propone serlo. (Abraham Lincoln)", source: "ConfiguroWeb"},
{quote:"Cada uno de los movimientos de todos los individuos se realizan por tres únicas razones: por honor, por dinero o por amor. (Napoleón I)", source: "ConfiguroWeb"},
{quote:"Cada uno es artífice de su propia ventura. (Cervantes)", source: "ConfiguroWeb"},
{quote:"Como a nadie se le puede forzar para que crea, a nadie se le puede forzar para que no crea. (Sigmund Freud)", source: "ConfiguroWeb"},
{quote:"Como artista mi autoestima proviene de realizar mi trabajo. No necesito ser rica pero necesito mucho aliento. No puedo permitir que mi vida intelectual o emocional se estanquen, o mi trabajo sufrirá. Mi vida y mi temperamento sufrirán: si no puedo crear me pongo de mal humor. (Julia Cameron)", source: "ConfiguroWeb"},
{quote:"Como el camino terreno está sembrado de espinas, Dios ha dado al hombre tres dones: la sonrisa, el sueño y la esperanza. (Inmanuel Kant)", source: "ConfiguroWeb"},
{quote:"Como un rayo láser, tu poder aumenta cuando enfocas tu atención y energía hacia el logro de objetivos especícos. (Leo Alcalá)", source: "ConfiguroWeb"},
{quote:"Como voy a vivir hoy para crear un mañana en el que estoy comprometido?. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"Crea una incapacidad e incapacitarás tu creatividad. (Jaime Tenorio Valenzuela)", source: "ConfiguroWeb"},
{quote:"Creo que existe solamente un mundo, y una sola realidad, que cada uno de nosotros contempla desde una posición única e intransferible en función de las heridas, y de los premios, con los que la vida nos haya marcado. (Almudena Grandes. (nacida en 1960), escritora española)", source: "ConfiguroWeb"},
{quote:"Creo que no existe ninguna cualidad tan esencial para el éxito como la perseverancia. Lo supera prácticamente todo, incluso a la naturaleza. (John D. Rockefeller)", source: "ConfiguroWeb"},
{quote:"Cualquier cosa que pase toma responsabilidad. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"Cualquier momento es bueno para un cambio; por ejemplo: Ahora. (Fredy Catú Diaz)", source: "ConfiguroWeb"},
{quote:"Cualquiera que no este cometiendo errores es que no está intentándolo lo suficiente. (Wess Roberts)", source: "ConfiguroWeb"},
{quote:"Cuan lejos puedes llegar en tu vida depende en que seas tender con los jovenes, tengas compasion por los ancianos, simpatia con los debiles y tolerante con los debiles y fuertes. Porque algun dia vos vas a ser uno de ellos. (George Washington.)", source: "ConfiguroWeb"},
{quote:"Cuando el ser humano ya tiene un por qué vivir siempre va ha encontrar el cómo vivir. (Víctor Frank)", source: "ConfiguroWeb"},
{quote:"Cuando hay un problema, no hay nada que hacer; hay algo que saber. (Raymond Charles Baker)", source: "ConfiguroWeb"},
{quote:"Cuando lo que haces te provoca dar lo mejor de ti sin esperar recompensa, haz encontrado tu vocación. (Gustavo Estrada Luque)", source: "ConfiguroWeb"},
{quote:"Cuando los recursos son escasos las oportunidades son únicas. (Anónimo)", source: "ConfiguroWeb"},
{quote:"Cuando se es joven, se crea. Cuando se es inteligente, se produce. No se adapta, se innova: la medianía copia; la originalidad se atreve. (José Marti)", source: "ConfiguroWeb"},
{quote:"Cuando un hombre sabe para donde va, el mundo entero se aparta para darle paso. (Bertrand Russell)", source: "ConfiguroWeb"},
{quote:"Cuando un poeta canta estamos en sus manos: él es el que sabe despertar en nosotros aquellas fuerzas secretas; sus palabras nos descubren un mundo maravilloso que antes no conocíamos. (Novalis)", source: "ConfiguroWeb"},
{quote:"De cada diez oportunidades que te da la vida nueve las produces tú. (Eilsen hawer)", source: "ConfiguroWeb"},
{quote:"Despierten, despierten, despierten no hay tiempo. (Sai Baba)", source: "ConfiguroWeb"},
{quote:"Duda del que quieras , pero nunca de ti mismo. (Christine Bovee.)", source: "ConfiguroWeb"},
{quote:"Edison se equivocó 10 mil veces antes de inventar la luz eléctrica. No te desanimes si llegas a fallar algunas veces. (Nicholas Murray Butler)", source: "ConfiguroWeb"},
{quote:"El 97% de las personas de gente muere sin haber vivido. (Madre Teresa)", source: "ConfiguroWeb"},
{quote:"El alcanza las murallas, pero no realiza ningún ataque. La fortuna se halla cerca. Se dan los primeros pasos para la reconciliación. El hombre sabio no comete la equivocación de atacar a sus oponentes, sabiendo que todo se solucionará pronto. (I CHING)", source: "ConfiguroWeb"},
{quote:"El amor crea en la mujer, una mujer nueva; la de la víspera ya no existe al día siguiente. (Honoré De Balzac)", source: "ConfiguroWeb"},
{quote:"El amor es un crimen que no puede realizarse sin cómplice. (Charles Baudelaire)", source: "ConfiguroWeb"},
{quote:"El amor inspira las más grandes hazañas e impide realizarlas. (Alejandro Dumas)", source: "ConfiguroWeb"},
{quote:"El amor tiene un duende que ríe, que enciende, que crea y recrea y aunque al diablo le pese, retoña y florece y al mal lo voltea. (Eladia Blazquez)", source: "ConfiguroWeb"},
{quote:"El arte de vencer se aprende en las derrotas. (Simón Bolívar)", source: "ConfiguroWeb"},
{quote:"El consumismo tiene una fuerte raíz en la publicidad masiva y en la oferta bombardeante que nos crea falsas necesidades. (Enrique Rojas)", source: "ConfiguroWeb"},
{quote:"El cuento de la pobreza, es mental. Cuando una persona es pobre externamente, es porque es pobre de pensamiento. Enséñele a pensar y vivirá en abundancia. (Linares)", source: "ConfiguroWeb"},
{quote:"El deseo intenso crea no sólo sus propias oportunidades sino además sus propios talentos. (Eric Hoffer)", source: "ConfiguroWeb"},
{quote:"El destino mezcla las cartas, y nosotros las jugamos. (Arthur Schopenhauer)", source: "ConfiguroWeb"},
{quote:"El destino no está escrito, se crea haciendo que se cree, pero tambien se crea no haciendo y se crea asi. (Victor Manuel Hernández Ugarte)", source: "ConfiguroWeb"},
{quote:"El dinero no crea ideas, sino melancolía. (Günter Grass)", source: "ConfiguroWeb"},
{quote:"El éxito encubre mil desaciertos. (George B. Shaw)", source: "ConfiguroWeb"},
{quote:"El éxito es la habilidad de ir de fracaso a fracaso sin perder el entusiasmo. (Winston Churchill)", source: "ConfiguroWeb"},
{quote:"El éxito está en la vida que uno lleva, en cómo vive, cómo goza, cómo se integra, cómo disfruta de las pequeñas cosas. (Laura Esquivel)", source: "ConfiguroWeb"},
{quote:"El éxito no es el resultado de una combustión espontánea. Tú tienes que encenderte primero. (Fred Shero)", source: "ConfiguroWeb"},
{quote:"El fracaso es solo la oportunidad de comenzar de nuevo de forma más inteligente. (Henry Ford)", source: "ConfiguroWeb"},
{quote:"El fracaso es un estado mental. Nadie ha fracasado a menos que lo acepte como realidad. Para mi el fracaso es temporario y su castigo es un llamado para que realize mas esfuerzo para llegar a mi meta. El fracaso solo me esta diciendo que estoy haciendo algo mal y esto me lleva al exito y la verdad. (Bruce Lee.)", source: "ConfiguroWeb"},
{quote:"El fracaso no exite, solo existen resultados. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"El genio es resultado de un uno por ciento de inspiración y de un noventa y nueve por ciento de transpiración. (Thomas Edison)", source: "ConfiguroWeb"},
{quote:"El gran negocio de la vida es pensar. Domine sus pensamientos y dominará sus circunstancias. (Adolfo Torres)", source: "ConfiguroWeb"},
{quote:"El hombre de 50 años que ve el mundo de la misma manera en que lo veía a los 20 años, ha desperdiciado 30 años de su vida. (Anónimo)", source: "ConfiguroWeb"},
{quote:"El hombre esta diseñado y formado para solucionar hasta los más grandes problemas, por ello jamás debemos ser cobardes y no enfrentar los problemas con la suficiente valentia. (Jaime Pérez)", source: "ConfiguroWeb"},
{quote:"El hombre más fuerte del mundo es el que está más solo. (Henrik Johan Ibsen)", source: "ConfiguroWeb"},
{quote:"El hombre más poderoso es el que es dueño de sí mismo. (Séneca)", source: "ConfiguroWeb"},
{quote:"El hombre más poderoso, es aquel que es totalmente, dueño de sí mismo. (Aristóteles)", source: "ConfiguroWeb"},
{quote:"El hombre no es nada más que su proyecto, no existe más que en la medida en que se realiza, no es, por lo tanto, más que el conjunto de sus actos, nada más que su vida. (Jean Paul Sartre)", source: "ConfiguroWeb"},
{quote:"El hombre no se da cuenta de cuánto puede hacer, más que cuando realiza intentos, medita y desea. (Ugo Foscolo)", source: "ConfiguroWeb"},
{quote:"El hombre que ha cometido un error y no lo corrige, comete otro error mayor. (Confucio)", source: "ConfiguroWeb"},
{quote:"El hombre que ha movido montañas comenzó siempre soñando que movería piedrecillas. (Marden)", source: "ConfiguroWeb"},
{quote:"El hombre se autorrealiza en la misma medida en que se compromete al cumplimiento del sentido de su vida. (Viktor Frankl)", source: "ConfiguroWeb"},
{quote:"El honor consiste en hacer hermoso aquello que uno está obligado a realizar. (Alfred Victor de Vigny)", source: "ConfiguroWeb"},
{quote:"El hundimiento de una creencia crea una nueva dimensión del sujeto, al obligarle a conducir su personalidad a lo largo de un eje situado fuera del plano de aquella. (Juan Benet)", source: "ConfiguroWeb"},
{quote:"El mayor mérito del hombre, consiste en determinar sus circunstancias y no dejar que las circunstancias, lo determinen a él. (Goethe)", source: "ConfiguroWeb"},
{quote:"El mejor modo de predecir el futuro es inventándolo. (Alan Key)", source: "ConfiguroWeb"},
{quote:"El miedo no existe en otro lugar excepto en la mente. (Dale Carnegie)", source: "ConfiguroWeb"},
{quote:"El mundo es un pensamiento realizado de la luz. Un pensamiento dichoso. (Juan Ortíz)", source: "ConfiguroWeb"},
{quote:"El progreso es la realización de las utopías. (Oscar Wilde)", source: "ConfiguroWeb"},
{quote:"El que siembra, cosecha. (Jesús)", source: "ConfiguroWeb"},
{quote:"El sabio puede sentarse en un hormiguero, pero sólo el necio se queda sentado en él. (Proverbio)", source: "ConfiguroWeb"},
{quote:"El secreto de mi éxito está en pagar como si fuera pródigo y vender como si estuviera en quiebra. (Henry Ford)", source: "ConfiguroWeb"},
{quote:"El secreto de mi gran éxito, fue rodearme de personas mejores que yo. (Andretv Carnegie)", source: "ConfiguroWeb"},
{quote:"el sentimiento se construye con actos que se realizan. (jean paul sartre)", source: "ConfiguroWeb"},
{quote:"El ser humano que hace más de aquello por lo que le pagan, pronto recibirá más de lo que hace. (Nicholas Murray Butler)", source: "ConfiguroWeb"},
{quote:"el sueño es la realizacion de un deseo. (Sigmund Freud)", source: "ConfiguroWeb"},
{quote:"El trabajo ayuda siempre, puesto que trabajar no es realizar lo que uno imaginaba, sino descubrir lo que uno tiene dentro. (Boris Leonídovich Pasternak)", source: "ConfiguroWeb"},
{quote:"El único límite a nuestros logros de mañana está en nuestras dudas de hoy. (Franklin D. Roosevelt)", source: "ConfiguroWeb"},
{quote:"El universo visible, es decir, la realización o encarnación del pensamiento divino es la causa ocasional de la ciencia. (Juan Valera)", source: "ConfiguroWeb"},
{quote:"El verdadero heroísmo consiste en persistir más de un momento cuando todo parece perdido. (Grenfel)", source: "ConfiguroWeb"},
{quote:"El victorioso tiene muchos amigos. El vencido, buenos amigos. (Proverbio Mongol)", source: "ConfiguroWeb"},
{quote:"El virtuoso se conforma con soñar lo que el pecador realiza en la vida. (Platón)", source: "ConfiguroWeb"},
{quote:"En cualquier momento de decisión lo mejor es hacer lo correcto, luego lo incorrecto, y lo peor es no hacer nada. (Theodore Roosevelt(1858-1919), presidente estadounidense)", source: "ConfiguroWeb"},
{quote:"En cualquier tipo de tarea creadora, la persona que crea se une con su material, que representa el mundo exterior a él. (Erich Fromm)", source: "ConfiguroWeb"},
{quote:"En estos momentos estas creando tu vida. (Neale Walsh)", source: "ConfiguroWeb"},
{quote:"En la vida necesitas inspiracion o desesperacion. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"En la vida, todo es amor. Si uno ama está vivo, si crea amor, las cosas buenas forzosamente llegan. (Ray Bradbury)", source: "ConfiguroWeb"},
{quote:"En mi experiencia hay solo una motivacion, es el deseo. No existe razon ni principio en contra de esto. (Jane Smiley)", source: "ConfiguroWeb"},
{quote:"En momento de crisis es cuando se demuestran nuestras fortalezas. (Desconocido)", source: "ConfiguroWeb"},
{quote:"En tanto que haya alguien que crea en una idea, la idea vive. (José Ortega Y Gasset)", source: "ConfiguroWeb"},
{quote:"En vez de lamentarte por las oportunidades perdidas, dedícate a crear nuevas oportunidades. (Anónimo)", source: "ConfiguroWeb"},
{quote:"Encontré mi motivación al mirar hacia arriba desde una SIMA y observar a todos andar en 2 pies; pensé que cuando llegue a la superficie alcanzar la CIMA será mas fácil porque sabrÉ utlizar aparte de mis pies; mis manos. (3dward0 - 66)", source: "ConfiguroWeb"},
{quote:"Envejecer es obligatorio, crecer es opcional. (Rosa)", source: "ConfiguroWeb"},
{quote:"Es absurdo continuar haciendo siempre lo mismo y esperar resultados diferentes . (Proverbio Oriental)", source: "ConfiguroWeb"},
{quote:"Es difícil cambiar pero no imposible, primero cuesta pero lo fundamental y básico es insistir. (Silvia Freire)", source: "ConfiguroWeb"},
{quote:"Es duro fracasar, pero es todavía peor no haber intentado nunca triunfar. (Theodore Roosevelt)", source: "ConfiguroWeb"},
{quote:"Es en los momentos de las decisions que nuestro destino es moldeado. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"Es importante que el pueblo de París no se crea que es la nación. (Napoleón Bonaparte)", source: "ConfiguroWeb"},
{quote:"Es intentando lo imposible como se realiza lo posible. (Henri Barbusse)", source: "ConfiguroWeb"},
{quote:"Es justamente la posibilidad de realizar un sueño lo que hace que la vida sea interesante. (Paulo Coelho)", source: "ConfiguroWeb"},
{quote:"Es verdaderamente libre aquel que desea solamente lo que es capaz de realizar y que hace lo que le agrada. (Jean Jacques Rousseau)", source: "ConfiguroWeb"},
{quote:"Escribo como medio y arma de combate, que combatir es realizar el pensamiento. (Domingo Faustino Sarmiento)", source: "ConfiguroWeb"},
{quote:"Están usando el 2% del cerebro. (Albert Einstein)", source: "ConfiguroWeb"},
{quote:"Existen dos maneras de ser feliz en esta vida, una es hacerse el idiota y la otra serlo. (Sigmund Freud)", source: "ConfiguroWeb"},
{quote:"Fija tus ojos hacia adelante en lo que puedes hacer, no hacia atras en lo que no puedes cambiar. (Tom Clancy)", source: "ConfiguroWeb"},
{quote:"Fuerza y equilibrio son parte de un mismo ser, usalas bien. (Matias Izquierdo)", source: "ConfiguroWeb"},
{quote:"Gozos, pesares, gozos... Esto es amor. Quien no lo crea, mírese en unos ojos, que se vea en unos ojos de mujer. (Vicente Gaos)", source: "ConfiguroWeb"},
{quote:"Hasta que no te valores a ti mismo no valoraras tu tiempo. Y hasta que no valores tu tiempo no harás nada con él. (M.Scott Peck)", source: "ConfiguroWeb"},
{quote:"Hay más divinidad en el arte que en la ciencia;la ciencia descubre, el arte crea. (John Opie)", source: "ConfiguroWeb"},
{quote:"Hay muchas mas oportunidades en busca de hombres capaces, que hombres capaces en busca de oportunidades. (Antiguo refrán)", source: "ConfiguroWeb"},
{quote:"Hay tres grupos de personas: los que hacen que las cosas pasen; los que miran las cosas que pasan y los que se preguntan qué pasó. (Nicholas Murray Butler)", source: "ConfiguroWeb"},
{quote:"Hay una fuerza motriz más poderosa que el vapor, la electricidad y la energía atómica. Esa fuerza es la voluntad. (Albert Einstein)", source: "ConfiguroWeb"},
{quote:"Hay una puerta por la que puede entrar la buena o la mala fortuna. Usted tiene la llave. (Proverbio japonés)", source: "ConfiguroWeb"},
{quote:"Haz lo necesario para lograr tu más ardiente deseo, y acabarás lográndolo. (Ludwig van Beethoven)", source: "ConfiguroWeb"},
{quote:"Haz lo que puedas, con lo que tengas, donde estés. (Theodore Roosevelt)", source: "ConfiguroWeb"},
{quote:"Haz sólo lo que amas y serás feliz, y el que hace lo que ama, está benditamente condenado al éxito, que llegará cuando deba llegar, porque lo que debe ser será, y llegará naturalmente. (Facundo Cabral)", source: "ConfiguroWeb"},
{quote:"He aprendido que cuando un hombre verdaderamente se realiza es por 4 fuertes razones: por honor, por dinero, por amor, y por bondad. (Michel Tanus Cruz)", source: "ConfiguroWeb"},
{quote:"He comprendido que mis fracasos del pasado y mis fustraciones son la fundacion de mis nuevos niveles de vida de alegria. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"He realizado observaciones y experimentos en el espacioso laboratorio del mundo con una maravillosa máquina portátil perfectamente ajustada en mi cabeza. (George Bernard Shaw)", source: "ConfiguroWeb"},
{quote:"La agenda es como un castillo de cartas, si retiras una todo se desmoronará. (Anónimo)", source: "ConfiguroWeb"},
{quote:"La confianza en sí mismo es el primer secreto del éxito. (Ralph Waldo Emerson.)", source: "ConfiguroWeb"},
{quote:"La crueldad misma está motivada por algo más profundo: el deseo de conocer el secreto de las cosas y de la vida. (Erich Fromm)", source: "ConfiguroWeb"},
{quote:"La disciplina es el mejor amigo del hombre, porque ella le lleva a realizar los anhelos más profundos de su corazón. (Madre Teresa De Calcuta)", source: "ConfiguroWeb"},
{quote:"La excelencia moral es resultado del hábito. Nos volvemos justos realizando actos de justicia; templados, realizando actos de templanza; valientes, realizando actos de valentía. (Aristóteles)", source: "ConfiguroWeb"},
{quote:"La gente a la que le va bien en la vida es la gente que va en busca de las circunstancias que quiere, y si no las encuentra, se las hace, se las fabrica. (George Bernard Shaw. (1856-1950), escritor irlandés)", source: "ConfiguroWeb"},
{quote:"La gloría no se escribe con palabras, se escribe con la vida. (Albizu)", source: "ConfiguroWeb"},
{quote:"La ilusión del amor es tan poderoso que al igual que la fuerza interna para realizar las cosas, hace que tu espiritu continue la jornada sin importar lo penosa que sea, sigues con sentimientos firmes y positivos, el intentarlo cada día vale la pena ya que asi me siento vivo. (Rozeti)", source: "ConfiguroWeb"},
{quote:"La juventud debe ejercitar los derechos que ha de realizar y enseñar después. (José Marti)", source: "ConfiguroWeb"},
{quote:"La libertad no es la licencia para realizar cualquier cosa. (Mahatma Gandhi)", source: "ConfiguroWeb"},
{quote:"La locura está en pretender obtener resultados diferentes haciendo siempre lo mismo. (Albert Einstein)", source: "ConfiguroWeb"},
{quote:"La manera como puedes desarrollar el hábito de tomar decisiones, es comenzar ahora mismo allí donde estás, con todos los interrogantes en frente de ti. (Nicholas Murray Butler)", source: "ConfiguroWeb"},
{quote:"La manera de atraer y motivar a las personas determina el éxito del líder. (Warren Bennis)", source: "ConfiguroWeb"},
{quote:"La manera efectiva de comunicarnos con los demas es tomar conciencia de todos percibimos el mundo de manera diferente por lo tanto utiliza esta guia para comunicarte con los demas. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"La mayoría de la gente fracasa no por falta de talento, dinero u oportunidad; fracasa porque nunca planifica por escrito. (Robert H. Shuller)", source: "ConfiguroWeb"},
{quote:"La mejor forma de conseguir la realización personal es dedicarse a metas desinteresadas. (Viktor Frankl)", source: "ConfiguroWeb"},
{quote:"La mejor parte de la vida, es compartir con los que te rodean, y dar sin esperar recibir nada a cambio, el destino solo se encargara de decidir en sus momento si alguien compartira sus vivencias contigo. (Dar es el mejor regalo que puedo recibir. (Rozeti)", source: "ConfiguroWeb"},
{quote:"La moda, nacida para uniformar, consigue que cada cual de quienes la siguen crea que así se diferencia del resto. (Lola Gavarrón)", source: "ConfiguroWeb"},
{quote:"La motivacion es el fuego interno. Si alguien trata de encender el fuego delante de ti , se quemara de seguro. (Stephen Covey)", source: "ConfiguroWeb"},
{quote:"La motivacion es lo que te ayuda a empezar. El habito te mantiene firme en tu camino. (Jim Ryun)", source: "ConfiguroWeb"},
{quote:"La motivación nos impulsa a comenzar y el hábito nos permite continuar. (Jim Ryum)", source: "ConfiguroWeb"},
{quote:"La necesidad de aliviar la tensión sólo motiva parcialmente la atracción entre los sexos; la motivación fundamental es la necesidad de unión con el otro polo sexual. (Erich Fromm)", source: "ConfiguroWeb"},
{quote:"La persona inteligente busca la experiencia que desea realizar. (Aldous Huxley)", source: "ConfiguroWeb"},
{quote:"La posibilidad de realizar un sueño es lo que hace que la vida sea interesante. (Paulo Coelho. (nacido en 1947), escritor y periodista brasileño)", source: "ConfiguroWeb"},
{quote:"La razón es fría, pero ve claro; la emoción le debe dar calor, pero sin hacer perder esa claridad. (J. Balmes)", source: "ConfiguroWeb"},
{quote:"La realidad en la que te encuentras puede ser alterada por ti en cualquier momento. No se altera al cambiar lo que está fuera de ti, se modifica cambiando como eliges procesar tu vida. (Wayne W. Dyer)", source: "ConfiguroWeb"},
{quote:"La realización de los premios de nuestra sociedad es ganada con el costo de una disminución de la Personalidad. (Carl Jung)", source: "ConfiguroWeb"},
{quote:"La sabiduría suprema es tener sueños bastante grandes para no perderlos de vista mientras se persiguen. (William Faulkner)", source: "ConfiguroWeb"},
{quote:"La suerte es el cruce de caminos donde la búsqueda se encuentra con la oportunidad. (Norman Vincent Peale)", source: "ConfiguroWeb"},
{quote:"La tragedia en la vida no consiste en no alcanzar tus metas. La tragedia en la vida es no tener metas que alcanzar. (Benjamin E. Mays)", source: "ConfiguroWeb"},
{quote:"La única persona que estará contigo toda la vida, eres tu mismo. Enfócate en tu camino y llegaras a lo que anhelas. (Dannyar)", source: "ConfiguroWeb"},
{quote:"La utopía está en el horizonte. Camino dos pasos, ella se aleja dos pasos y el horizonte se corre diez pasos más allá. ¿Entonces para que sirve la utopía? Para eso, sirve para caminar. (Eduardo Galeano)", source: "ConfiguroWeb"},
{quote:"La verdad es totalmente interior. No hay que buscarla fuera de nosotros ni querer realizarla luchando con violencia contra enemigos exteriores. (Mahatma Gandhi)", source: "ConfiguroWeb"},
{quote:"La vida es demasiado corta para ser pequeña. (Benjamín Disraeli)", source: "ConfiguroWeb"},
{quote:"La vida es passion!. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"la vida es tan corta, q se necesitarian varias, para poder realizar los suenos q anhelamos... (josabe)", source: "ConfiguroWeb"},
{quote:"La vida es una oportunidad, beneficiate de ella. La vida es belleza, admirala. La vida es un sueño, alcanzalo. La vida es un desafio, enfrentalo, La vida es un juego, juegalo. (Mother Teresa)", source: "ConfiguroWeb"},
{quote:"La violencia crea más problemas sociales que los que resuelve. (Martin Luther King)", source: "ConfiguroWeb"},
{quote:"Las circunstancias no definen a la persona, ellas simplemente la revelan, la exponen ante sí misma. (Víctor Frank)", source: "ConfiguroWeb"},
{quote:"Las creencias tienen el poder de crear y de destruir. Los seres humanos tienen la abilidad de tomar una experiencia en sus vidad y crear un significado destructivo o salvar sus vidas. (Anthony Robbins.)", source: "ConfiguroWeb"},
{quote:"Las espadas que realizan las mayores conquistas son las que tienen diamantes incrustados. (Georg Christoph Lichtenberg)", source: "ConfiguroWeb"},
{quote:"Las oportunidades solamente las aprovechan las mentes preparadas. (Luis Pasteur)", source: "ConfiguroWeb"},
{quote:"Las tonterías dejan de serlo cuando son realizadas de forma atrevida por gente con sensibilidad. (Jane Austen)", source: "ConfiguroWeb"},
{quote:"Las únicas limitaciones son aquellas que nos imponemos. (Nicholas Murray Butler)", source: "ConfiguroWeb"},
{quote:"Lo malo de hacer sugerencias inteligentes es que te elijan para realizarlas. (Anónimo)", source: "ConfiguroWeb"},
{quote:"Lo principal es tener el valor de admitir nuestros errores y la fuerza de voluntad para corregirlos en el tiempo más breve posible. (J. Stalin)", source: "ConfiguroWeb"},
{quote:"Lo que importa es cuanto amor ponemos en el trabajo que realizamos. (Madre Teresa de Calcuta)", source: "ConfiguroWeb"},
{quote:"Los chinos utilizan dos pinceladas para escribir la palabra crisis. Una pincelada significa “peligro. (y la otra “oportunidad”, por lo tanto en una crisis toma conciencia del peligro, pero reconoce la oportunidad. (John Kennedy)", source: "ConfiguroWeb"},
{quote:"Los chinos utilizan dos pinceladas para escribir la palabra crisis. Una pincelada significa peligro la otra oportunidad. En una crisis toma conciencia del peligro pero reconoce la oportunidad. (John Kennedy)", source: "ConfiguroWeb"},
{quote:"Los juicios de los demas no crea mi realidad... (Eugenio Ramon Riveros)", source: "ConfiguroWeb"},
{quote:"Los obstáculos son productos de nuestra propia mente. (Nelson Mandela)", source: "ConfiguroWeb"},
{quote:"Mientras uno de los dos no crea posible una ruptura, el amor prevalecerá... (Dibi)", source: "ConfiguroWeb"},
{quote:"Mientras usted no ponga sus metas en papel tendrá intenciones que son semillas sin tierra. (Anónimo)", source: "ConfiguroWeb"},
{quote:"Mira tus manos, muévelas. Y te darás cuenta del poder con el que cuentas. (Dannyar)", source: "ConfiguroWeb"},
{quote:"Muchas cosas se reputan imposibles antes de haberse realizado. (Plinio El Viejo)", source: "ConfiguroWeb"},
{quote:"Muchos de nuestros sueños parecen al principio imposibles, luego pueden parecer improbables, y luego, cuando nos comprometemos firmemente, se vuelven inevitables. (Christopher Reeve)", source: "ConfiguroWeb"},
{quote:"Muchos sueñan y desean, pero son pocos los valientes que se atreven a vivir sus sueños. (Desconocido)", source: "ConfiguroWeb"},
{quote:"Nada es demasiado difícil si se lo divide en pequeñas tareas. (Ford)", source: "ConfiguroWeb"},
{quote:"Nada hay imposible; hay caminos que conducen a todo. Si tuviera la suficiente voluntad, contaría siempre con los medios necesarios. (La Roche faucauld)", source: "ConfiguroWeb"},
{quote:"Nada puede detener a un hombre que posee la actitud mental correcta, para lograr sus sueños, nada en la tierra puede ayudar al hombre que posea una actitud mental equivocada. (W. W. Ziege)", source: "ConfiguroWeb"},
{quote:"Nada sobre esta tierra puede detener al hombre que posee la correcta actitud mental para lograr su meta. Nada sobre esta tierra puede ayudar al hombre con la incorrecta actitud mental. (Thomas Jefferson)", source: "ConfiguroWeb"},
{quote:"Nadie es dueño de la multitud aunque crea tenerla dominada. (Eugene Ionesco)", source: "ConfiguroWeb"},
{quote:"Necesito autoridad, aunque no crea en ella. (Ernst Jünger)", source: "ConfiguroWeb"},
{quote:"Ningún hombre es feliz a menos que crea serlo. (Publio Siro)", source: "ConfiguroWeb"},
{quote:"Ningun hombre ha sido sabio de casualidad. (Seneca)", source: "ConfiguroWeb"},
{quote:"Ningún pesimista ha descubierto nunca el secreto de las estrellas, o navegado hacia una tierra sin descubrir, o abierto una nueva esperanza en el corazón humano. (Hellen Keller)", source: "ConfiguroWeb"},
{quote:"No canto para ser feliz, soy feliz porque canto. (William James)", source: "ConfiguroWeb"},
{quote:"No es la política la que crea extraños compañeros de cama, sino el matrimonio. (Groucho Marx)", source: "ConfiguroWeb"},
{quote:"No es lo que obtenemos sino lo que contribuimos lo que le da un significado a nuestras vidas. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"No es lo que tu tienes, sino como usas lo que tienes lo que marca la diferencia. (Zig Ziglar)", source: "ConfiguroWeb"},
{quote:"No es valiente quien no tiene miedo, sino quien sabe vencerlo. (Nelson Mandela)", source: "ConfiguroWeb"},
{quote:"No esperes por el éxito si eso es lo que quieres; haz lo que realmente amas y cree en ello y el éxito vendrá naturalmente. (David Frost)", source: "ConfiguroWeb"},
{quote:"No esperes por el momento preciso. Empieza ahora. Hazlo ahora. Si esperas por el momento adecuado, nunca dejarás de esperar. . (Jasmine Gillman)", source: "ConfiguroWeb"},
{quote:"No esperes que pase la tormenta, aprende a bailar bajo la lluvia. (Proverbio sufí)", source: "ConfiguroWeb"},
{quote:"No hay nada que dé más dirección a la vida de una persona que un gran conjunto de principios. (Emerson)", source: "ConfiguroWeb"},
{quote:"No hay tiempo para aburrirte cuando decides vivir intensamente tu vida. (Dannyar)", source: "ConfiguroWeb"},
{quote:"No hay un grito de dolor que en el futuro no tenga al fin como eco una alegría. (Anónimo)", source: "ConfiguroWeb"},
{quote:"No he trabajado ni un día en toda mi vida. Todo fue diversión. (Thomas Edison)", source: "ConfiguroWeb"},
{quote:"No puedes dar lo que no tienes, no puedes pedir lo que no mereces. (Anónimo)", source: "ConfiguroWeb"},
{quote:"No puedes escapar de la responsabilidad de mañana evadiéndola hoy. (Abraham Lincoln)", source: "ConfiguroWeb"},
{quote:"No robes: de esta manera no tendrás nunca suerte en los negocios. Haz trampas. (Ambrose Bierce)", source: "ConfiguroWeb"},
{quote:"No son las circunstancias sino tu opinión sobre ellas lo que te afecta profundamente. (Epiteto)", source: "ConfiguroWeb"},
{quote:"No son los eventos en nuestra vidas lo que nos moldean, sino nuestras creencias con respecto a esos eventos. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"No soporto al artista cuya principal motivación sea la provocación. Creo que los grandes provocadores lo son sin proponérselo. (Pedro Almodóvar)", source: "ConfiguroWeb"},
{quote:"No sucede nada bueno que no haya sido alguna vez un sueño. (Cari Sandburg)", source: "ConfiguroWeb"},
{quote:"No te asuste naufragar que el tesoro que buscamos, capitán, no está en el seno del puerto sino en el fondo del mar. (León Felipe)", source: "ConfiguroWeb"},
{quote:"No te conviertas en esclavo de tu ser inferior. Tú puedes controlar tus pensamientos, no asumas que es inevitable el que ellos te controlen desde aquellas falsas ideas que provienen de voces inferiores. En ti habitan dos seres, uno inferior y uno superior. Deja que el ser superior govierne tu vida, aquel ser de pensamientos elevados, libre de mesquindades y dramillas cotidianos. (Ana C Blum)", source: "ConfiguroWeb"},
{quote:"No te des por vencido, ni aún vencido . (Desconocido)", source: "ConfiguroWeb"},
{quote:"No te preocupes por lo que no tienes. Ocúpate, disfruta, aprovecha, y valora todo lo que aún tienes. Tu vida, tu tiempo, tu mente, tu cuerpo, tus conocimientos, en fin tienes una infinidad de recursos que siempre estarán contigo. (Dannyar)", source: "ConfiguroWeb"},
{quote:"Nuestra naturaleza consiste en el movimiento; el reposo absoluto es la muerte. (B. Pascal)", source: "ConfiguroWeb"},
{quote:"Nuestra tarea consiste en animar a cristianos y no cristianos a realizar obras de amor. Y cada obra de amor, hecha de todo corazón, acerca a las personas a Dios. (Madre Teresa de Calcuta)", source: "ConfiguroWeb"},
{quote:"Nuestras horas son minutos cuando esperamos saber, y siglos cuando sabemos lo que se puede aprender. (Antonio Machado)", source: "ConfiguroWeb"},
{quote:"Nunca crea nada hasta que no haya sido negado oficialmente. (Claud Cockburn)", source: "ConfiguroWeb"},
{quote:"Nunca te quejes del ambiente o de los que te rodean, hay quienes en tu mismo ambiente supieron vencer, las circunstancias son buenas o malas según la voluntad o fortaleza de tu corazón. (Pablo Neruda)", source: "ConfiguroWeb"},
{quote:"Para alcanzar el águila con una flecha, hay que apuntarle a la luna. (Og Mandino)", source: "ConfiguroWeb"},
{quote:"Para que los cambios tengan un valor verdadero deben ser consistentes y duraderos. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"Para vivir existen tres métodos: mendigar, robar o realizar algo. (Conde de Mirabeau)", source: "ConfiguroWeb"},
{quote:"Pensar es fácil, actuar es un poco más difícil, pero actuar como se piensa es lo más difícil de todo. (Goethe)", source: "ConfiguroWeb"},
{quote:"Piense en grande y sus hechos crecerán. Piense en pequeño y quedará atrás. Piense que puede y podrá. Todo está en su actitud mental. (Christian Barnard)", source: "ConfiguroWeb"},
{quote:"Pobre no es el hombre cuyos sueños no se han realizado, sino aquel que no sueña. (Marie Von Ebner Eschenbach)", source: "ConfiguroWeb"},
{quote:"Podrás perderlo todo pero menos tus conocimientos, aprovéchalos. (Dannyar)", source: "ConfiguroWeb"},
{quote:"Podré perder la vida pero la vida no me la pierdo. (Sandro)", source: "ConfiguroWeb"},
{quote:"Podrían ser dioses y eligen ser mendigos. (Pitágoras)", source: "ConfiguroWeb"},
{quote:"Porque nadie puede saber por ti. Nadie puede crecer por ti. Nadie puede buscar por ti. Nadie puede hacer por ti lo que tu mismo debes hacer. La existencia no admite representantes. (Jorge Bucay)", source: "ConfiguroWeb"},
{quote:"Porque veo, al final de mi rudo camino, que yo fui el arquitecto de mi propio destino. (Amado Nervo)", source: "ConfiguroWeb"},
{quote:"Preocupate más por tu carácter que por tu reputación. Tu carácter es lo que realmente eres, mientras que tu reputación es solo lo que los otros creen que tú eres. (Dale Carnegie)", source: "ConfiguroWeb"},
{quote:"Prohibir crea tentaciones. (Anónimo)", source: "ConfiguroWeb"},
{quote:"Quien crea que su propia vida y la de sus semejantes está privada de significado no es sólo infeliz, sino que apenas es capaz de vivir. (Albert Einstein)", source: "ConfiguroWeb"},
{quote:"Quien sólo busca el aplauso de los demás, pone su felicidad en manos ajenas. (Oliver Goldsmith)", source: "ConfiguroWeb"},
{quote:"Realiza cada una de tus acciones como si fuera la última de tu vida. (Marco Aurelio)", source: "ConfiguroWeb"},
{quote:"Recuerda que la verdadera decision es medida por el hecho de haber tomado accion. Si no hay accion no has tomado una decision. La manera en que nos comunicamos con los demas y con nostros mismos determina la calidad de nuestras vidas. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"Recuerda, hoy es el mañana acerca del cual te preocupabas ayer. (Dale Carnegie)", source: "ConfiguroWeb"},
{quote:"Saber que se puede es el mejor principio para realizar tus sueños.. (Yazmin)", source: "ConfiguroWeb"},
{quote:"Se alcanza el éxito convirtiendo cada paso en una meta y cada meta en un paso. (C. C. Cortez)", source: "ConfiguroWeb"},
{quote:"Se alegraron con tu nacimiento, tú llorabas; vive de manera que puedas jusgarte realizado en el momento de tu muerte, pra ver llorar a los otros. (Proverbio Persa)", source: "ConfiguroWeb"},
{quote:"Ser disciplinado como esclavo crea el temperamento esperado de esclavos… Golpear a los niños y aplicarles otros tipos de castigo corporal no es la herramienta apropiada para quien busca formar hombres inteligentes, buenos y sabios. (John Locke)", source: "ConfiguroWeb"},
{quote:"Serás del tamaño de tus pensamientos, piensa en grande. (Donald Trump)", source: "ConfiguroWeb"},
{quote:"Si bien la acción no trae la felicidad, no hay felicidad sin acción. (Benjamín Disraeli)", source: "ConfiguroWeb"},
{quote:"Si en verdad amas la vida, no derroches tu tiempo porque éste es la materia prima de la cual la vida está hecha. (Benjamín Franklin)", source: "ConfiguroWeb"},
{quote:"Si existe algo extraordinario como el universo, también puede haber un ser humano tan extraordinario como el universo. (Dannyar)", source: "ConfiguroWeb"},
{quote:"Si no te gusta lo que te sucede, cambielo , tu no eres un árbol. (Jim Rohn)", source: "ConfiguroWeb"},
{quote:"Si pierde su riqueza, no ha perdido nada; Si pierde su salud, habrá perdido algo; Pero si pierde su paz interior, lo habrá perdido todo. (Pensamiento Oriental)", source: "ConfiguroWeb"},
{quote:"Si poco a poco te vas superando, debes entender que más te fortaleces, y que más posibilidades tienes de poder superar desafíos mas grandes. (Desconocido)", source: "ConfiguroWeb"},
{quote:"Si pudieramos conocer el resultado de nuestras acciones antes de realizarlas, no existiría el arrepentimiento. (Cantervill)", source: "ConfiguroWeb"},
{quote:"Si queremos dirigir nuestras vidas debemos tomar control de nuestras acciones. No es lo que hacemos una vez lo que moldea nuestra vida sino lo que hacemos consistentemente. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"Si quieres conocer a un hombre libre, observa a aquel que crea. (Doménico Cieri Estrada)", source: "ConfiguroWeb"},
{quote:"Si siempre haces lo que siempre hiciste obtendras lo que siempre obtuviste. (Anthony Robbins)", source: "ConfiguroWeb"},
{quote:"Si su vida cotidiana le parece pobre, no se queje de ella; quéjese de usted mismo, dígase que no es bastante poeta como para configurar sus riquezas. (Rilke)", source: "ConfiguroWeb"},
{quote:"Si tienes un sueño en tu corazón, y de verdad crees en él, corres el riesgo de que se convierta en realidad. (Walt Disney)", source: "ConfiguroWeb"},
{quote:"Si tuviéramos que hablar más que escuchar, tendríamos dos bocas y solamente una oreja. (Mark Twain)", source: "ConfiguroWeb"},
{quote:"Si una persona sabe lo que desea de la vida cumple todos los requisitos para conseguir realizar un sueño. (Paulo Coelho)", source: "ConfiguroWeb"},
{quote:"Si uno avanza confiadamente en la dirección de sus sueños y deseos para llevar la vida que ha imaginado, se encontrará con un éxito inesperado. (Henry David Thoreau)", source: "ConfiguroWeb"},
{quote:"Si usted desea ser entusiasta, tiene que actuar en forma entusiasta. (Dale Carnegie)", source: "ConfiguroWeb"},
{quote:"Siembra una idea y cosecharás un deseo; siembra un deseo y cosecharás una acción; siembra una acción y cosecharás un hábito; siembra un hábito y cosecharás un carácter; siembra un carácter y cosecharás un destino. (William James)", source: "ConfiguroWeb"},
{quote:"Solamente hay una esquina del universo que tu puedes mejorar, y esa esquina eres tu mismo. (Aldous Huxley)", source: "ConfiguroWeb"},
{quote:"Solo aquellos que se atreven a tener grandes fracasos terminan consiguiendo grandes éxitos. (Robert F. Kennedy)", source: "ConfiguroWeb"},
{quote:"Solo el que sabe independizarse de las personas, sabrá amarlas como son. (Antony de Mello)", source: "ConfiguroWeb"},
{quote:"Sólo es capaz de realizar los sueños el que, cuando llega la hora, sabe estar despierto. (León Daudí)", source: "ConfiguroWeb"},
{quote:"Solo hay dos formas de vivir tu vida. Una es pensar que nada es un milagro. La otra es pensar que todo es un milagro. (Albert Einstein)", source: "ConfiguroWeb"},
{quote:"Sólo hay dos palancas que muevan a los hombres: el miedo y el interés. (Napoleón I)", source: "ConfiguroWeb"},
{quote:"Sólo los que se atreven a la incertidumbre del éxito terminan consiguiéndolo. (Leo Alcalá)", source: "ConfiguroWeb"},
{quote:"Sólo triunfa en el mundo quien se levanta y busca a las circunstancias y las crea si no las encuentra. (George Bernard Shaw)", source: "ConfiguroWeb"},
{quote:"Sólo una cosa convierte en imposible un sueño: el miedo a fracasar. (Paulo Coelho)", source: "ConfiguroWeb"},
{quote:"Somos dueños de nuestro destino. Somos capitanes de nuestra alma. (Winston Churchill)", source: "ConfiguroWeb"},
{quote:"Somos el producto de nuestros pensamientos. Lo que viene de adentro nos construye. Si solamente creamos amarguras, rencores y negaciones, pues nuestra vida sera una casa siempre en ruinas. Si por el contrario somos creadores de amor, alegrías y certezas, nuestra casa sera una construcción bella y solida, rodeada de flores y arboles frondosos. (acb)", source: "ConfiguroWeb"},
{quote:"Somos la esencia del libro de la vida, somos los autores y editores de nuestra historia, no existen secuelas solo una parte, queda de nosotros el hacer una comedia o tragedia de ella. (Andy Alfonso)", source: "ConfiguroWeb"},
{quote:"Somos lo que hacemos día a día. De modo que la excelencia no es un acto, sino un hábito. (Aristóteles)", source: "ConfiguroWeb"},
{quote:"Somos los únicos seres que podemos cambiar nuestra biología con nuestro pensamiento. (Albert Einstein)", source: "ConfiguroWeb"},
{quote:"Son capaces, porque creen que son capaces. (Virgilio)", source: "ConfiguroWeb"},
{quote:"Soy un paranoico al revés. Siempre sospecho que la gente está planeando algo para hacerme feliz. (Jerome David Salinger)", source: "ConfiguroWeb"},
{quote:"Tanto si crees que puedes hacerlo, como si no, en los dos casos tienes razón. (Henry Ford)", source: "ConfiguroWeb"},
{quote:"Te convertirás en alguien tan pequeño como el deseo que te controle, y en algo tan grande como sea tu aspiración dominante. (James Allen)", source: "ConfiguroWeb"},
{quote:"Ten un fuerte motivo para existir, no busques sólo llegar, busca siempre seguir. (Carlos de la Rosa-Vidal)", source: "ConfiguroWeb"},
{quote:"Tenemos que ser nosotros la expresión de nuestra proposición. (Mahatma Gandhi)", source: "ConfiguroWeb"},
{quote:"Toda acción natural está realizada por la naturaleza misma del modo y en el tiempo más breve posible. Ninguna acción natural puede abreviarse, pues la naturaleza la genera del modo más breve posible. (Leonardo Da Vinci)", source: "ConfiguroWeb"},
{quote:"Toda la actividad humana está motivada por el deseo o el impulso. (Bertrand Russell)", source: "ConfiguroWeb"},
{quote:"Toda lectura debe ir acompañada de meditación, es la única manera de encontrar en los libros lo que otros no supieron hallar en ellos. (Levaye)", source: "ConfiguroWeb"},
{quote:"Todas las guerras son santas, os desafío a que encontréis un beligerante que no crea tener el cielo de su parte. (Jean Anouilh)", source: "ConfiguroWeb"},
{quote:"Todo aquello que puedas o sueñes hacer, comiénzalo. La audacia contiene en si misma genio, poder y magia. (Goethe)", source: "ConfiguroWeb"},
{quote:"Todo aquello que usted puede proyectar, lo puede realizar. Las limitaciones sólo existen en su pensamiento. (Og Mandino)", source: "ConfiguroWeb"},
{quote:"Todo el mundo trata de realizar algo grande, sin darse cuenta de que la vida se compone de cosas pequeñas. (Frank Clark)", source: "ConfiguroWeb"},
{quote:"Todo gran proyecto, debe tener un principio, pero es en la continuidad, hasta el final, en dónde se obtiene la verdadera ganancia. (Linares)", source: "ConfiguroWeb"},
{quote:"Todo lo que el espiritu desea, el espiritu alcanza. (Kahlil Gibran)", source: "ConfiguroWeb"},
{quote:"Todo lo que la mente puede concebir y creer, la mente puede alcanzar. (Napoleón)", source: "ConfiguroWeb"},
{quote:"Todo lo que usted vívidamente imagine, ardientemente desee, sinceramente crea y con entusiasmo emprenda...Inevitablemente Le sucederá. (Paul J. Meyer)", source: "ConfiguroWeb"},
{quote:"Todo lo verás, según el color del cristal con que lo mires. (Calderón de la Barca)", source: "ConfiguroWeb"},
{quote:"Todo obstáculo o problema lleva en su interior la semilla de un beneficio equivalente o mayor. (Napoleón Hill)", source: "ConfiguroWeb"},
{quote:"Todos tus sueños pueden hacerse realidad si tienes el coraje de perseguirlos. (Walt Disney)", source: "ConfiguroWeb"},
{quote:"Todos, al menos por un momento experimentamos la realización de nuestro sueño. (Edgar López Vargas)", source: "ConfiguroWeb"},
{quote:"Triste pero es así. La gente busca algo en que creer, dáselo y te elegirán como su lider. (Tonino Licciardello Bernabé, gurú informático)", source: "ConfiguroWeb"},
{quote:"Tú eres una persona de éxito cuando tienes algunas de las cosas que el dinero puede comprar y todas las cosas que el dinero no puede comprar. (Zig Ziglar)", source: "ConfiguroWeb"},
{quote:"Un campeón tiene miedo de perder. Los demás tienen miedo de ganar. (Billie Jean King)", source: "ConfiguroWeb"},
{quote:"Un error no se convierte en verdad por el hecho de que todo el mundo crea en él. (Mahatma Gandhi)", source: "ConfiguroWeb"},
{quote:"Un objetivo, una meta, un blanco, sirven para determinar la acción de hoy y obtener el resultado de mañana. (Peter Drucker)", source: "ConfiguroWeb"},
{quote:"Un poco de conocimiento que actua es mucho mas valioso que tener conocimiento y no actuar. (Kahlil Gibran)", source: "ConfiguroWeb"},
{quote:"Una derrota no es el peor fracaso. No haberlo intentado es el verdadero fracaso. (George Edward Woodberry)", source: "ConfiguroWeb"},
{quote:"Una experiencia bien realizada es siempre positiva. (Gastón Bachelard)", source: "ConfiguroWeb"},
{quote:"Una persona no puede directamente escoger sus circunstancias, pero si puede escoger sus pensamientos e indirectamente -y con seguridad- darle forma a sus circunstancias. (James Allen)", source: "ConfiguroWeb"},
{quote:"Una persona usualmente se convierte en aquello que el cree que es. Si yo sigo diciéndome a mi mismo que no puedo hacer algo, es posible que yo termine siendo incapaz de hacerlo. Por el contrario si yo tengo la creencia que sí puedo hacerlo, con seguridad yo adquiriré la capacidad de realizarlo aunque no la haya tenido al principio. (Gandhi)", source: "ConfiguroWeb"},
{quote:"Una sonrisa es una línea curva que lo endereza todo. (Phyllis Diller)", source: "ConfiguroWeb"},
{quote:"Una vida lograda es un sueño de adolescente realizado en la edad madura. (Alfred Victor de Vigny)", source: "ConfiguroWeb"},
{quote:"Usted puede cambiar su mundo. (Napoleón Hill)", source: "ConfiguroWeb"},
{quote:"Usted tiene el pincel y los colores. Pinte el paraíso y entre después en él. (Nikos Kanzan tzakis)", source: "ConfiguroWeb"},
{quote:"Visión sin Acción, es un sueño. Acción sin Visión, es pasar el tiempo. Acción con Visión, es lo que hace la diferencia. (Joel Barker)", source: "ConfiguroWeb"},
{quote:"Viviré este día como si fuera el último de mi existencia. (Og Mandino)", source: "ConfiguroWeb"},
{quote:"Yo honro con el nombre de virtud a la costumbre de realizar acciones penosas y útiles a los demás. (Stendhal)", source: "ConfiguroWeb"},
{quote:"Yo nunca perdí o fracase, yo aún no vencí. Si me caigo siete veces, me levantaré ocho. (Desconocido)", source: "ConfiguroWeb"},
{quote:"Yo te amaré en silencio... como algo inaccesible, como un sueño que nunca lograré realizar y el lejano perfume de mi amor imposible rozará tus cabellos... y jamás lo sabrás. (José Angel Buesa)", source: "ConfiguroWeb"},
{quote:"A los afligidos no se les ha de añadir aflicción. (Miguel De Cervantes)", source: "ConfiguroWeb"},
{quote:"Acuérdate de conservar en los acontecimientos graves la mente serena. (Horacio)", source: "ConfiguroWeb"},
{quote:"Admiro la cabeza que sabe llevar con altivez la desgracia, como un rey la corona. (Carlo Bini)", source: "ConfiguroWeb"},
{quote:"Al lado de la dificultad está la facilidad. (Mahoma)", source: "ConfiguroWeb"},
{quote:"Atribuimos a la casualidad nuestras desgracias, jamás nuestra prosperidad. (Charles Régismanset)", source: "ConfiguroWeb"},
{quote:"Aunque nunca obres mal, no por eso escaparás al dolor alguna vez. (Menandro)", source: "ConfiguroWeb"},
{quote:"Cada cual tiene sus penas; todos están condenados igualmente a gemir: el compasivo por los sufrimientos ajenos, el egoísta por los propios. (Thomas Gray)", source: "ConfiguroWeb"},
{quote:"Cuando el corazón es bueno, el dolor es saludable. (Alfred De Musset)", source: "ConfiguroWeb"},
{quote:"Cuando el infortunio se generaliza en un país, se hace universal el egoísmo. (Montesquieu)", source: "ConfiguroWeb"},
{quote:"Cuando la adversidad llama a tu puerta, todos los amigos están dormidos. (Proverbio Polaco)", source: "ConfiguroWeb"},
{quote:"Cuando la desgracia se asoma a la ventana, los amigos no se acercan a mirar. (Proverbio Alemán)", source: "ConfiguroWeb"},
{quote:"Cuando la situación es adversa y la esperanza poca, las determinaciones fuertes son las más seguras. (Tito Livio)", source: "ConfiguroWeb"},
{quote:"Cuando no se puede sufrir algo, lo mejor es saberlo sufrir. (Séneca)", source: "ConfiguroWeb"},
{quote:"Cuando se está en medio de las adversidades, ya es tarde para ser cauto. (Séneca)", source: "ConfiguroWeb"},
{quote:"Cuando todo va mal, no debe ser tan malo probar lo peor. (Francis H. Bradley)", source: "ConfiguroWeb"},
{quote:"Cuanto más se dividen los obstáculos son más fáciles de vencer. (Concepción Arenal)", source: "ConfiguroWeb"},
{quote:"El día en que tus desgracias hayan aprendido el camino de tu casa, múdate. (Juan Manuel De Palacio)", source: "ConfiguroWeb"},
{quote:"El dolor es esencial a la vida y no proviene del exterior, sino que cada uno lo llevamos dentro de nosotros mismos, como un manantial que no se agota. (Arthur Schopenhauer)", source: "ConfiguroWeb"},
{quote:"El dolor es más llamativo que la felicidad. (Ana María Matute)", source: "ConfiguroWeb"},
{quote:"El dolor siempre cumple lo que promete. (Madame De Staël)", source: "ConfiguroWeb"},
{quote:"El dolor silencioso es el más funesto. (Jean Racine)", source: "ConfiguroWeb"},
{quote:"El dolor, si grave, es breve; si largo, es leve. (Cicerón)", source: "ConfiguroWeb"},
{quote:"El gozo fecunda, el dolor engendra. (William Blake)", source: "ConfiguroWeb"},
{quote:"El hombre es un aprendiz: el dolor es su eterno maestro. (Alfred De Musset)", source: "ConfiguroWeb"},
{quote:"El hombre está más organizado para el dolor que para placer. (Anthelme Brillant-Savarin)", source: "ConfiguroWeb"},
{quote:"El hombre no toma conciencia de su ser más que en las situaciones límite. (Karl Jaspers)", source: "ConfiguroWeb"},
{quote:"El hombre que no sufre es una máquina mal compuesta, una criatura defectuosa, un mutilado moral, un aborto de la naturaleza. (Charles Tellier)", source: "ConfiguroWeb"},
{quote:"El hombre que soporta con lamentos la adversidad se causa a sí mismo mayor pena. (Franz Schubert)", source: "ConfiguroWeb"},
{quote:"El hombre se descubre cuando se mide con un obstáculo. (Antoine De Saint-Exupéry)", source: "ConfiguroWeb"},
{quote:"El hombre segrega la fuerza en proporción con su infortunio. (Chris Marker)", source: "ConfiguroWeb"},
{quote:"El más rápido corcel para llegar a la perfección es el sufrimiento. (Johannes Eckhart)", source: "ConfiguroWeb"},
{quote:"El mayor dolor del mundo, no es el que mata de un golpe, sino aquel que, gota a gota, horada el alma y la rompe. (Francisco Villaespesa)", source: "ConfiguroWeb"},
{quote:"El mejor modo de resolver una dificultad es no tratar de soslayarla. (Noel Clarasó)", source: "ConfiguroWeb"},
{quote:"El mundo se ha reído de sus propias tragedias, como único medio de soportarlas. (Oscar Wilde)", source: "ConfiguroWeb"},
{quote:"El que pueda decir cómo arde, sufre un fuego muy pequeño. (Francesco Petrarca)", source: "ConfiguroWeb"},
{quote:"El que teme padecer padece ya lo que teme. (Michel E. De Montaigne)", source: "ConfiguroWeb"},
{quote:"El secreto de ser desdichado estriba en tener tiempo de pensar en si se es, o no, feliz. (George Bernard Shaw)", source: "ConfiguroWeb"},
{quote:"El sufrimiento purifica. Aquel que sepa sufrir mejor, hará mejor obra. (John Milton)", source: "ConfiguroWeb"},
{quote:"En la adversidad de nuestros mejores amigos siempre encontramos alguna cosa que no nos desagrada del todo. (François De La Rochefoucauld)", source: "ConfiguroWeb"},
{quote:"En la desgracia conviene tomar algún camino atrevido. (Séneca)", source: "ConfiguroWeb"},
{quote:"En las adversidades sale a la luz la virtud. (Aristóteles)", source: "ConfiguroWeb"},
{quote:"En una vida sin penas, acaban por relajarse las cuerdas del alma. (Johannes Kepler)", source: "ConfiguroWeb"},
{quote:"Es un gran privilegio haber vivido una vida difícil. (Indira Gandhi)", source: "ConfiguroWeb"},
{quote:"Es una ley: sufrir para comprender. (Esquilo)", source: "ConfiguroWeb"},
{quote:"Fácil es alegrarse en la prosperidad, pero verdaderamente es varonil el hombre que sonríe ante el infortunio. (Orison S. Marden)", source: "ConfiguroWeb"},
{quote:"Fácil es en la adversidad despreciar la muerte; más valor demuestra el que sabe ser desgraciado. (Marcial)", source: "ConfiguroWeb"},
{quote:"Fatiga menos caminar sobre terrero accidentado que sobre terreno llano. (Aristóteles)", source: "ConfiguroWeb"},
{quote:"Gozan los ánimos fuertes en las adversidades, al igual que los soldados intrépidos triunfan en las guerras. (Séneca)", source: "ConfiguroWeb"},
{quote:"Hay gentes que padecen tres clases de tribulación: la que tuvieron, la que tienen y la que esperan tener. (Orison S. Marden)", source: "ConfiguroWeb"},
{quote:"He sido un hombre afortunado: nada en la vida me fue fácil. (Sigmund Freud)", source: "ConfiguroWeb"},
{quote:"La adversidad depende menos de los males que sufrimos que de la imaginación con que los padecemos. (François Fénelon)", source: "ConfiguroWeb"},
{quote:"La adversidad vuelve sabio al hombre. (Séneca)", source: "ConfiguroWeb"},
{quote:"La desdicha es grande, pero el hombre es aún más grande que la desdicha. (Rabindranath Tagore)", source: "ConfiguroWeb"},
{quote:"La desgracia es ocasión para la virtud. (Séneca)", source: "ConfiguroWeb"},
{quote:"La desgracia le hace a uno virtuoso. La virtud nunca la hubiera inventado un hombre feliz. (Charles Régismanset)", source: "ConfiguroWeb"},
{quote:"La desgracia no quebranta al hombre valiente. (Séneca)", source: "ConfiguroWeb"},
{quote:"La desgracia termina por amainar. Los vientos no siempre soplan del mismo cuadrante ni con igual fuerza. (Eurípides)", source: "ConfiguroWeb"},
{quote:"La desgracia, como la piedad, suele terminar haciéndose hábito. (Graham Greene)", source: "ConfiguroWeb"},
{quote:"La experiencia de la desgracia me enseñó a socorrer al desgraciado. (Oscar Wilde)", source: "ConfiguroWeb"},
{quote:"La manera más profunda de sentir una cosa es sufrir por ella. (Gustave Flaubert)", source: "ConfiguroWeb"},
{quote:"La mayor desgracia es merecer la desgracia. (Jean De La Fontaine)", source: "ConfiguroWeb"},
{quote:"La mayoría de la gente gasta más tiempo y energías en esquivar los problemas que en tratar de resolverlos. (Henry Ford)", source: "ConfiguroWeb"},
{quote:"La mayoría de las desgracias son peores como amenaza que como realidad. (Montesquieu)", source: "ConfiguroWeb"},
{quote:"La prosperidad no existe sin temores ni disgustos, ni la adversidad sin consuelos y esperanzas. (Francis Bacon)", source: "ConfiguroWeb"},
{quote:"La tragedia está en los ojos del que la contempla, no en el corazón del que sufre. (Ralph W. Emerson)", source: "ConfiguroWeb"},
{quote:"La vida en sí es corta, pero la desgracia la hace larga. (Publio Siro)", source: "ConfiguroWeb"},
{quote:"Lamentar un infortunio pasado, y que no existe, es la más segura vía de crearse otro infortunio. (William Shakespeare)", source: "ConfiguroWeb"},
{quote:"Las desdichas crecen las firmezas. (Félix Lope De Vega)", source: "ConfiguroWeb"},
{quote:"Las dificultades están hechas para estimular y no para quitar el ánimo. El espíritu humano debe fortificarse en la lucha. (William E. Channing)", source: "ConfiguroWeb"},
{quote:"Las fatigas de la vida nos enseñan únicamente a apreciar los bienes de la vida. (Johann W. Goethe)", source: "ConfiguroWeb"},
{quote:"Lleva tu cruz cantando y no suspirando. En todo mercado vale más una sonrisa que mil lamentos. (Charles Lamb)", source: "ConfiguroWeb"},
{quote:"Los golpes de la adversidad son muy amargos, pero nunca estériles. (Joseph E. Renan)", source: "ConfiguroWeb"},
{quote:"Los grandes sufrimientos se exacerban a la vista de lo que podría aliviarlos. (William Shakespeare)", source: "ConfiguroWeb"},
{quote:"Los hombres y los reyes deben juzgarse por los momentos críticos de sus vidas. (Sir Winston Churchill)", source: "ConfiguroWeb"},
{quote:"Los males imaginarios no existen. Todos los males son reales desde el momento en que se experimentan; soñar el dolor es un dolor verdadero. (Anatole France)", source: "ConfiguroWeb"},
{quote:"Los que no han sufrido nunca no saben nada. No conocen ni el bien ni el mal; no conocen a los hombres ni se conocen a sí mismos. (François Fénelon)", source: "ConfiguroWeb"},
{quote:"Los sufrimientos del alma nos elevan; los del cuerpo nos abaten. (Giuseppe Giusti)", source: "ConfiguroWeb"},
{quote:"Mejor que combatir una desgracia es, a veces, tratar de ser feliz dentro de ella. (Maurice Maeterlinck)", source: "ConfiguroWeb"},
{quote:"No es valiente el que hace frente a la muerte, sino el que impávido soporta la desgracia. (Philip Massinger)", source: "ConfiguroWeb"},
{quote:"No hay dolor más grande que el de acordarse del tiempo feliz en la desgracia. (Dante Alighieri)", source: "ConfiguroWeb"},
{quote:"No hay mayor dolor que el que no habla. (Henry W. Longfellow)", source: "ConfiguroWeb"},
{quote:"No son las grandes desgracias las que debemos temer en la vida, sino las pequeñas. (Gustave Flaubert)", source: "ConfiguroWeb"},
{quote:"Nos gusta más comentar nuestras desgracias que callarlas. (François De La Rochefoucauld)", source: "ConfiguroWeb"},
{quote:"Quien no ha afrontado la adversidad no conoce su propia fuerza. (Ben Jonson)", source: "ConfiguroWeb"},
{quote:"Sabiendo sufrir se sufre menos. (Anatole France)", source: "ConfiguroWeb"},
{quote:"Se sufre menos del dolor mismo que de la manera como se le acepta. (Maurice Maeterlinck)", source: "ConfiguroWeb"},
{quote:"Si fueras tan juicioso que resistieras de buen grado los pequeños males de la vida, no te verías tantas veces obligado a soportar otros mayores. (Christian F. Gellert)", source: "ConfiguroWeb"},
{quote:"Si llegas a ser desgraciado, ocúltalo para que tus enemigos no se alegren. (Periandro)", source: "ConfiguroWeb"},
{quote:"Somos tan pequeños como nuestra dicha, pero somos tan grandes como nuestro dolor. (Ch. Friedrich Hebbel)", source: "ConfiguroWeb"},
{quote:"Soporta y resiste: ese esfuerzo te será muy útil un día. (Ovidio)", source: "ConfiguroWeb"},
{quote:"También el dolor desea desahogarse; el hombre abrumado por el dolor no siente vergüenza de sus lágrimas. (Friedrich M. Von Bodenstedt)", source: "ConfiguroWeb"},
{quote:"Tengamos buen ánimo y recordemos que las desgracias más insoportables son aquellas que nunca llegan. (James R. Lowell)", source: "ConfiguroWeb"},
{quote:"Toda dificultad eludida se convertirá más tarde en un fantasma que perturbará nuestro reposo. (Frédéric Chopin)", source: "ConfiguroWeb"},
{quote:"Todos tenemos fuerzas suficientes para soportar los males ajenos. (François De La Rochefoucauld)", source: "ConfiguroWeb"},
{quote:"Un hombre acostumbrado a las adversidades no es fácilmente sorprendido. (Samuel Johnson)", source: "ConfiguroWeb"},
{quote:"Un hombre es la suma de sus desdichas. Se podría creer que la desdicha terminará un día por cansarse, pero entonces es el tiempo el que se convierte en nuestra desdicha. (William Faulkner)", source: "ConfiguroWeb"},
{quote:"Un problema deja de serlo si no tiene solución. (Eduardo Mendoza)", source: "ConfiguroWeb"},
{quote:"Un pueblo con vida, por diezmado que se encuentre, extrae de la adversidad médula y fuerzas. (Henrik Ibsen)", source: "ConfiguroWeb"},
{quote:"¿Qué es el bien? No es más que amor. (León Tolstoi)", source: "ConfiguroWeb"},
{quote:"A fin de que seas mejor, purifícate todos los días. (Proverbio Chino)", source: "ConfiguroWeb"},
{quote:"A la buena gente se la conoce en que resulta mejor cuando se la conoce. (Bertolt Brecht)", source: "ConfiguroWeb"},
{quote:"A los hombres no les mueve el mérito de la buena acción, si no lleva tras sí el premio. (Ovidio)", source: "ConfiguroWeb"},
{quote:"Al bien hacer jamás le falta premio. (Miguel De Cervantes)", source: "ConfiguroWeb"},
{quote:"Buscando el bien de nuestros semejantes, encontramos el nuestro. (Platón)", source: "ConfiguroWeb"},
{quote:"Como llegan lejos los rayos de aquella pequeña bujía, así brilla una buena acción en un mundo salvaje. (William Shakespeare)", source: "ConfiguroWeb"},
{quote:"Cuando soy buena, soy buena; cuando soy mala, soy mucho mejor. (Mae West)", source: "ConfiguroWeb"},
{quote:"Cuando una persona no comprende instintivamente lo que es bueno y lo que es malo, es un tonto o un granuja. (George Bernard Shaw)", source: "ConfiguroWeb"},
{quote:"Cuando veas un hombre bueno, piensa en imitarlo; cuando veas uno malo, examina tu propio corazón. (Confucio)", source: "ConfiguroWeb"},
{quote:"Cuanto mejor es una persona, más difícilmente sospecha de la maldad de los demás. (Cicerón)", source: "ConfiguroWeb"},
{quote:"Dar la felicidad y hacer el bien, he ahí nuestra ley, nuestra ancla de salvación, nuestro faro, nuestra razón de ser. (Henri-Frédéric Amiel)", source: "ConfiguroWeb"},
{quote:"El bien que hemos hecho nos da una satisfacción interior que es la más dulce de todas las pasiones. (René Descartes)", source: "ConfiguroWeb"},
{quote:"El bien que hicimos la víspera es el que nos trae la felicidad por la mañana. (Proverbio Indio)", source: "ConfiguroWeb"},
{quote:"El buen hombre es el maestro del malo, y el mal hombre es la lección del bueno. (Lao-Tsê)", source: "ConfiguroWeb"},
{quote:"El mal pago añade mérito a las buenas obras. (Jacinto Benavente)", source: "ConfiguroWeb"},
{quote:"El mejor homenaje que puede tributarse a las personas buenas es imitarlas. (Concepción Arenal)", source: "ConfiguroWeb"},
{quote:"El primer paso hacia el bien es no hacer el mal. (Jean-Jacques Rousseau)", source: "ConfiguroWeb"},
{quote:"El que se ocupa demasiado de hacer el bien, no tiene tiempo de ser bueno. (Rabindranath Tagore)", source: "ConfiguroWeb"},
{quote:"El que tiene lo bastante para poder hacer bien a otros, es rico. (Sir Thomas Browne)", source: "ConfiguroWeb"},
{quote:"El ruido no hace bien; el bien no hace ruido. (San Vicente De Paúl)", source: "ConfiguroWeb"},
{quote:"En este mundo, hace falta sólo ser un poco bueno para serlo bastante. (Pierre De Marivaux)", source: "ConfiguroWeb"},
{quote:"Entregarnos a los demás es desvivirnos. (Miguel De Unamuno)", source: "ConfiguroWeb"},
{quote:"Es bueno pensar rectamente. Es divino obrar así. (Horace Mann)", source: "ConfiguroWeb"},
{quote:"Es fácil ser bueno; lo difícil es ser justo. (Victor Hugo)", source: "ConfiguroWeb"},
{quote:"Es más deseable cultivar el respeto al bien que el respeto a la ley. (Henry D. Thoreau)", source: "ConfiguroWeb"},
{quote:"Es menester ser bueno, no por amor a los hombres, sino para estar en paz consigo mismo. (Achille Tournier)", source: "ConfiguroWeb"},
{quote:"Es mil veces más fácil hacer el bien que hacerlo bien. (Montesquieu)", source: "ConfiguroWeb"},
{quote:"Haced el bien a vuestros amigos y enemigos, porque así conservaréis los unos y os será posible atraer a los otros. (Cleóbulo)", source: "ConfiguroWeb"},
{quote:"Haz bien tu parte. En eso reside todo el honor. (Alexander Pope)", source: "ConfiguroWeb"},
{quote:"La alegría de hacer bien está en sembrar, no en recoger. (Jacinto Benavente)", source: "ConfiguroWeb"},
{quote:"La bondad de corazón y la equidad de un hombre honesto vale cien veces más que la amistad de un bellaco. (Jean-Jacques Rousseau)", source: "ConfiguroWeb"},
{quote:"La bondad es lo que importa, pues es el bálsamo que pone un poco de suavidad en cualquier amarga llaga. (San Pío X)", source: "ConfiguroWeb"},
{quote:"La bondad -no el genio, ni la gloria, ni el amor- es lo que refleja la grandeza del alma humana. (Henri Lacordaire)", source: "ConfiguroWeb"},
{quote:"La mejor vida no es la más larga, sino la más rica en buenas acciones. (Marie Curie)", source: "ConfiguroWeb"},
{quote:"La recompensa de una buen acción es haberla hecho. (Séneca)", source: "ConfiguroWeb"},
{quote:"Las buenas acciones refrescan la sangre y dan sueños felices. (Filippo Pananti)", source: "ConfiguroWeb"},
{quote:"Lo bueno no es bueno cuando se espera algo mejor. (Thomas Fuller)", source: "ConfiguroWeb"},
{quote:"Los hombres somos más capaces de grandes acciones que de buenas acciones. (Montesquieu)", source: "ConfiguroWeb"},
{quote:"Los hombres son crueles, pero el hombre es bueno. (Rabindranath Tagore)", source: "ConfiguroWeb"},
{quote:"Más quiero ser malo con esperanza de ser bueno, que bueno con el propósito de ser malo. (Miguel De Cervantes)", source: "ConfiguroWeb"},
{quote:"Muchas veces para ser buenos tenemos que dejar de ser honrados. (Jacinto Benavente)", source: "ConfiguroWeb"},
{quote:"Nada es bueno o malo, sino que el pensamiento es lo que hace las cosas buenas o malas. (William Shakespeare)", source: "ConfiguroWeb"},
{quote:"No basta con hacer el bien: hay que hacerlo bien. (Denis Diderot)", source: "ConfiguroWeb"},
{quote:"No conozco ningún otro signo de superioridad que la bondad. (Ludwig Van Beethoven)", source: "ConfiguroWeb"},
{quote:"No debemos lamentar nunca el tiempo que hemos empleado en proceder bien. (Joseph Joubert)", source: "ConfiguroWeb"},
{quote:"No es difícil para un hombre hacer algunas buenas acciones; lo difícil es obrar bien toda la vida, sin hacer nunca ningún mal. (Mao Tse-Tung)", source: "ConfiguroWeb"},
{quote:"No esperes al Juicio Final. Tiene lugar todos los días. (Ludwig Börne)", source: "ConfiguroWeb"},
{quote:"No puede ser bueno el que no sabe luchar y resistir. (Concepción Arenal)", source: "ConfiguroWeb"},
{quote:"No saber mostrarse bueno con los malos es una prueba de que no es uno bueno del todo. (San Francisco De Sales)", source: "ConfiguroWeb"},
{quote:"No se pierde el tiempo que se emplea en procurar hacer el bien. (Concepción Arenal)", source: "ConfiguroWeb"},
{quote:"No se puede ser bueno a medias. (León Tolstoi)", source: "ConfiguroWeb"},
{quote:"No te juzgues salvado por tu sola bondad. (Ramón Llull)", source: "ConfiguroWeb"},
{quote:"No todos los hombres pueden ser ilustres, pero pueden ser buenos. (Confucio)", source: "ConfiguroWeb"},
{quote:"Por lo general, los seres humanos quieren ser buenos, pero no demasiado buenos, y no todo el tiempo. (George Orwell)", source: "ConfiguroWeb"},
{quote:"Proponerse ser bueno es serlo ya. (Edme P. Beauchêne)", source: "ConfiguroWeb"},
{quote:"Que el hombre sea noble, caritativo y bueno, puesto que sólo esto lo distingue de todos los otros seres. (Johann W. Goethe)", source: "ConfiguroWeb"},
{quote:"Quien hace el bien desinteresadamente siempre es pagado con usura. (Johann W. Goethe)", source: "ConfiguroWeb"},
{quote:"Si hago una buena obra, me siento bien; y si obro mal, me encuentro mal. Esta es mi religión. (Abraham Lincoln)", source: "ConfiguroWeb"},
{quote:"Si quieres algo bueno, búscalo en ti mismo. (Epicteto)", source: "ConfiguroWeb"},
{quote:"Si un rostro hermoso es una carta de recomendación, un buen corazón es una letra de crédito. (George Bulwer-Lytton)", source: "ConfiguroWeb"},
{quote:"Sobre todo sé bueno: la bondad, más que ninguna otra cosa, es lo que mejor desarma a los hombres. (Henri Lacordaire)", source: "ConfiguroWeb"},
{quote:"Son las almas bellas las únicas que saben lo que hay de grande en la bondad. (François Fénelon)", source: "ConfiguroWeb"},
{quote:"Un benefactor es el que me hace bien, incluso aunque haga mal a todo el mundo. (Proverbio Árabe)", source: "ConfiguroWeb"},
{quote:"Una de las ventajas de las buenas acciones es la de elevar el alma y disponerla a hacer otras mejores. (Jean-Jacques Rousseau)", source: "ConfiguroWeb"},
{quote:"Una prueba de la propia bondad está en confiar en la bondad de los demás. (Michel E. De Montaigne)", source: "ConfiguroWeb"},
{quote:"¡Dinero y crédito! Dos cosas raras. Se tiene necesidad de dinero cuando no se posee, y se cuenta con crédito, especialmente, cuando no se tiene necesidad de él. (Moisés G. Saphir)", source: "ConfiguroWeb"},
{quote:"¿De qué puede servirnos la riqueza, si no la logramos en la edad en que se disfruta de ella? (Los envidiosos morirán, pero la envidia es inmortal. (Molière)", source: "ConfiguroWeb"},
{quote:"¿Para qué sirve el dinero? Al que no lo tiene le falta valor; el que lo posee tiene preocupaciones; el que lo disfrutó tiene pesar. (Barón De Logau)", source: "ConfiguroWeb"},
{quote:"¿Qué es la riqueza? Nada, si no se gasta; nada, si se mal gasta. (Manuel Bretón De Los Herreros)", source: "ConfiguroWeb"},
{quote:"¿Quieres ser rico? Pues no te afanes en aumentar tus bienes, sino en disminuir tu codicia. (Epicuro)", source: "ConfiguroWeb"},
{quote:"Algún dinero evita preocupaciones; mucho, las atrae. (Confucio)", source: "ConfiguroWeb"},
{quote:"Aquel que se enriquece rápidamente no será muy inocente. (Salomón)", source: "ConfiguroWeb"},
{quote:"Aquellos que tienen medios piensan que lo más importante en la vida es el amor. Los pobres saben que es el dinero. (Gerald Brenan)", source: "ConfiguroWeb"},
{quote:"Bienaventurado el que tiene talento y dinero, porque empleará bien este último. (Menandro)", source: "ConfiguroWeb"},
{quote:"Buena es la riqueza en la que no hay pecado; mala la pobreza al decir del impío. (Eclesiástico)", source: "ConfiguroWeb"},
{quote:"Con dinero se puede comprar todo, menos la felicidad, que es mucho más barata y mucho más cara a la vez. (Noel Clarasó)", source: "ConfiguroWeb"},
{quote:"Con el dinero sucede lo mismo que con el papel higiénico: cuando se necesita, se necesita urgentemente. (Upton Sinclair)", source: "ConfiguroWeb"},
{quote:"Cuando los ricos se hacen la guerra, son los pobres los que mueren. (Jean-Paul Sartre)", source: "ConfiguroWeb"},
{quote:"Cuando no se tiene dinero, siempre se piensa en él. Cuando el dinero se tiene, sólo se piensa en él. (Paul Getty)", source: "ConfiguroWeb"},
{quote:"Cuando se trata de dinero, todos son de la misma religión. (Voltaire)", source: "ConfiguroWeb"},
{quote:"Dinero compartido aumenta el amor, dinero regalado lo mata. (Stendhal)", source: "ConfiguroWeb"},
{quote:"Dos clases de hombres se esfuerzan en vano: quien amontona dinero sin gastarlo y quien adquiere saber sin aplicarlo. (Saadi)", source: "ConfiguroWeb"},
{quote:"El capital no es un mal en sí mismo. El mal radica en su mal uso. (Mahatma Gandhi)", source: "ConfiguroWeb"},
{quote:"El deseo de dinero crece tanto como el dinero mismo. (Juvenal)", source: "ConfiguroWeb"},
{quote:"El dinero ayuda a soportar la pobreza. (Alphonse Allais)", source: "ConfiguroWeb"},
{quote:"El dinero consagrado a la beneficencia no tiene mérito si no representa un sacrificio, una privación. (Cesare Cantú)", source: "ConfiguroWeb"},
{quote:"El dinero es como un sexto sentido; sin él no podríamos desarrollar los otros cinco. (William S. Maugham)", source: "ConfiguroWeb"},
{quote:"El dinero es igual al estiércol; sólo sirve si es esparcido. (Proverbio Inglés)", source: "ConfiguroWeb"},
{quote:"El dinero es tu esclavo si sabes emplearlo; tu amo, si no sabes. (Publio Siro)", source: "ConfiguroWeb"},
{quote:"El dinero es un buen sirviente, pero un pésimo maestro. (Francis Bacon)", source: "ConfiguroWeb"},
{quote:"El dinero habla un lenguaje que entienden todas las naciones. (Aphra Behn)", source: "ConfiguroWeb"},
{quote:"El dinero lo ganan todos aquellos que con paciencia y fina observación van detrás de los que lo pierden. (Benito Pérez Galdós)", source: "ConfiguroWeb"},
{quote:"El dinero no da la felicidad, pero aplaca los nervios. (Mistinguett)", source: "ConfiguroWeb"},
{quote:"El dinero no debe entrar en casa de las gentes honradas más que por la puerta de la virtud. (Jacques Amyot)", source: "ConfiguroWeb"},
{quote:"El dinero no habla, jura. (Bob Dylan)", source: "ConfiguroWeb"},
{quote:"El dinero no nos proporciona amigos sino enemigos de mejor calidad. (Noël Coward)", source: "ConfiguroWeb"},
{quote:"El dinero no puede hacer que seamos felices, pero es lo único que nos compensa de no serlo. (Jacinto Benavente)", source: "ConfiguroWeb"},
{quote:"El dinero pasa al correr por muchos lodazales. (Jacinto Benavente)", source: "ConfiguroWeb"},
{quote:"El dinero se adquiere con trabajo, se guarda con temor y se pierde con gravísimo dolor. (Casiodoro)", source: "ConfiguroWeb"},
{quote:"El dinero siempre está ahí, sólo cambian los bolsillos. (Gertrude Stein)", source: "ConfiguroWeb"},
{quote:"El dinero vale por veinte oradores. (William Shakespeare)", source: "ConfiguroWeb"},
{quote:"El dinero, venga de donde venga, huele bien. (Juvenal)", source: "ConfiguroWeb"},
{quote:"El hombre es rico desde que se ha familiarizado con la escasez. (Epicuro)", source: "ConfiguroWeb"},
{quote:"El hombre ha de escoger entre ser rico en cosas o en la libertad de usarlas. (Iván Illich)", source: "ConfiguroWeb"},
{quote:"El hombre próspero es como el árbol: la gente lo rodea cuando está cubierto de frutos; pero en cuanto los frutos han caído, la gente se dispersa en busca de un árbol mejor. (Anónimo)", source: "ConfiguroWeb"},
{quote:"El más rico de todos los hombres es el ahorrativo; el más pobre, el avaro. (Chamfort)", source: "ConfiguroWeb"},
{quote:"El mayor placer que la riqueza confiere consiste en la capacidad de ayudar a los demás. (André Maurois)", source: "ConfiguroWeb"},
{quote:"El mundo valora poco lo que paga poco. (Luigi Settembrini)", source: "ConfiguroWeb"},
{quote:"El oro circula porque tiene valor, pero el papel moneda tiene valor porque circula. (Karl Marx)", source: "ConfiguroWeb"},
{quote:"El oro es como las mujeres, que todos dicen mal de ellas y todos las desean. (Félix Lope De Vega)", source: "ConfiguroWeb"},
{quote:"El oro, a la par que es el más puro de los metales, es el mayor de los corruptores. (Joseph Sanial-Dubay)", source: "ConfiguroWeb"},
{quote:"El precio que tenemos que pagar por el dinero se paga en libertad. (Robert L. Stevenson)", source: "ConfiguroWeb"},
{quote:"El tener mucho dinero tan sólo sirve para ser los más ricos del cementerio. (Tonino Licciardello Bernabé, gurú informático)", source: "ConfiguroWeb"},
{quote:"El tesoro que no se gasta aprovecha poco. (Proverbio Árabe)", source: "ConfiguroWeb"},
{quote:"", source: "ConfiguroWeb"},
{quote:"En casa llena, presto se guisa la cena. (Miguel De Cervantes)", source: "ConfiguroWeb"},
{quote:"En el origen de todas las fortunas hay cosas que hacen temblar. (Louis Bourdaloue)", source: "ConfiguroWeb"},
{quote:"Eso de que el dinero no da la felicidad son voces que hacen correr los ricos para que no les envidien demasiado los pobres. (Jacinto Benavente)", source: "ConfiguroWeb"},
{quote:"Generalmente se juzgan los hombres por el crédito que disfrutan o por las riquezas que poseen. (François De La Rochefoucauld)", source: "ConfiguroWeb"},
{quote:"Grandes riquezas, gran esclavitud. (Séneca)", source: "ConfiguroWeb"},
{quote:"Hay ocasiones en que es más ventajoso experimentar un quebranto que un lucro. (Plauto)", source: "ConfiguroWeb"},
{quote:"Hay personas que de sus riquezas no tienen más que el miedo a perderlas. (Rivarol)", source: "ConfiguroWeb"},
{quote:"Hay que conocer el valor del dinero: los pródigos no lo conocen y los avaros menos aún. (Montesquieu)", source: "ConfiguroWeb"},
{quote:"Hay tan pocas grandes fortunas libres de culpa, que yo perdono a vuestros padres el que no os hayan dejado ninguna. (Marquesa De Lambert)", source: "ConfiguroWeb"},
{quote:"La actitud correcta hacia el dinero es de codicioso desdén. (Henry Miller)", source: "ConfiguroWeb"},
{quote:"La esperanza de que mañana seremos más ricos ¿compensa la impotencia de ser hoy más pobres? (Cuando el herrero no da en el clavo, es un errero. (Anónimo)", source: "ConfiguroWeb"},
{quote:"La esperanza de que mañana seremos más ricos ¿compensa la impotencia de ser hoy más pobres? (Los errores que hay que evitar son aquellos que eliminan la posibilidad de volverlo a intentar. (Anónimo)", source: "ConfiguroWeb"},
{quote:"La igualdad en la riqueza debe consistir en que ningún ciudadano sea tan opulento que pueda comprar a otro, ni ninguno tan pobre que se vea precisado a venderse. (Jean-Jacques Rousseau)", source: "ConfiguroWeb"},
{quote:"La opulencia tiene su miseria: es cobarde y se apega a la vida. (Eurípides)", source: "ConfiguroWeb"},
{quote:"La riqueza consiste en el uso adecuado de los bienes. (Plutarco)", source: "ConfiguroWeb"},
{quote:"La riqueza consiste mucho más en el disfrute que en la posesión. (Aristóteles)", source: "ConfiguroWeb"},
{quote:"La riqueza de un país no la hace un pequeño número de fortunas colosales, sino la multiplicidad de fortunas mediocres. (Stendhal)", source: "ConfiguroWeb"},
{quote:"La riqueza es como el agua salada: cuanto más se bebe, más sed da; lo mismo ocurre con la gloria. (Arthur Schopenhauer)", source: "ConfiguroWeb"},
{quote:"La riqueza es para el que la disfruta, y no para el que la guarda. (Proverbio Afgano)", source: "ConfiguroWeb"},
{quote:"La salud de muchos hubiera sido mejor si sus riquezas hubieran sido menores. (Benjamin Franklin)", source: "ConfiguroWeb"},
{quote:"Las ganancias mal logradas reportan pérdidas. (Eurípides)", source: "ConfiguroWeb"},
{quote:"Lo difícil es ganar miles honradamente. Los millones se amontonan sin trabajo. (Nicolai V. Gogol)", source: "ConfiguroWeb"},
{quote:"Los cambios súbitos de fortuna tienen un gran inconveniente: los enriquecidos no han aprendido a ser ricos, ni los arruinados a ser pobres. (Joseph Joubert)", source: "ConfiguroWeb"},
{quote:"Los hombres son pervertidos no tanto por la riqueza, cuanto por el afán de riqueza. (Vizconde De Bonald)", source: "ConfiguroWeb"},
{quote:"Los hombres tienen la piedra de toque para probar el oro; pero el oro es la piedra de toque para probar a los hombres. (Thomas Fuller)", source: "ConfiguroWeb"},
{quote:"Los moribundos que hablan de su testamento pueden confiar en ser escuchados como si fueran oráculos. (Jean De La Bruyère)", source: "ConfiguroWeb"},
{quote:"Los que conocen todas sus riquezas son pobres; solamente es rico aquel que no sabría decir cuánto posee. (Sir John Suckling)", source: "ConfiguroWeb"},
{quote:"Los ricos que no saben usar de sus riquezas son de una pobreza incurable, porque es pobreza de espíritu. (Jenofonte)", source: "ConfiguroWeb"},
{quote:"Me he dado cuenta de que las personas que no respetan el dinero no lo tienen. (Paul Getty)", source: "ConfiguroWeb"},
{quote:"Mirad al dinero por encima del hombro, pero jamás lo perdáis de vista. (Sacha Guitry)", source: "ConfiguroWeb"},
{quote:"Nada es más peligroso que la riqueza sin poder. (Ernst Jünger)", source: "ConfiguroWeb"},
{quote:"Ni la incuria puede envilecer a las almas fuertes, ni la riqueza elevar a los espíritus mezquinos. (Marqués De Vauvenargues)", source: "ConfiguroWeb"},
{quote:"No contemos el dinero ganado; ya hemos perdido bastante tiempo ganándolo. (George Bernard Shaw)", source: "ConfiguroWeb"},
{quote:"No estimes el dinero en más ni menos de lo que vale, porque es un buen siervo y un mal amo. (Alejandro Dumas)", source: "ConfiguroWeb"},
{quote:"No existe fortaleza alguna, por más defendida que esta esté, que no pueda conquistarse con dinero. (Cicerón)", source: "ConfiguroWeb"},
{quote:"No hay dinero en la poesía, tampoco hay poesía en el dinero. (Robert Graves)", source: "ConfiguroWeb"},
{quote:"No hay nadie que viva tan preocupado por el dinero como los ricos, si se exceptúa a los pobres. (Enrique Jardiel Poncela)", source: "ConfiguroWeb"},
{quote:"No podéis otorgar la fuerza al débil debilitando al fuerte; no podéis ayudar al pobre arruinando al rico. (Abraham Lincoln)", source: "ConfiguroWeb"},
{quote:"Nuestros padres nos dan la vida, pero el dinero es el único que nos la conserva. (Ihara Saikaku)", source: "ConfiguroWeb"},
{quote:"Nunca hizo rico al hombre el dinero, porque solamente le sirve para aumentar su codicia. (Séneca)", source: "ConfiguroWeb"},
{quote:"Obra muy mal quien trata de obtener con el dinero lo que debe obtener con la virtud. (Cicerón)", source: "ConfiguroWeb"},
{quote:"Para amasar una fortuna no se requiere ingenio, lo que es preciso es carecer de delicadeza. (Caballero De Bruix)", source: "ConfiguroWeb"},
{quote:"Por oro no vendas lo que nunca podrás comprar con oro: la tranquila siesta, el satisfecho día, la limpia fama y la conciencia alegre. (Samuel Johnson)", source: "ConfiguroWeb"},
{quote:"Preferirás la pobreza dentro de la justicia a la abundancia procurada mediante la iniquidad. (Teognis)", source: "ConfiguroWeb"},
{quote:"Que el no tener cofres llenos, la riqueza en pie mantiene, que no es rico el que más tiene, sino el que ha menester menos. (Tirso De Molina)", source: "ConfiguroWeb"},
{quote:"Quien ha perdido sus bienes puede decir: «Mis parientes han muerto.» (Cada persona forja su propia grandeza. Los enanos permanecerán enanos aunque se suban a los Alpes. (August Von Kotzebue)", source: "ConfiguroWeb"},
{quote:"Rico y de repente, no puede ser santamente. (Proverbio Castellano)", source: "ConfiguroWeb"},
{quote:"Saber cuándo uno dispone de lo suficiente es ser rico. (Lao-Tsê)", source: "ConfiguroWeb"},
{quote:"Se quitan las ganas de trabajar cuando uno se da cuenta de que el dinero no lo gana sino quien lo dilapida. (Sinibaldo De Mas)", source: "ConfiguroWeb"},
{quote:"Si alguna vez ven saltar por la ventana a un banquero suizo, salten detrás. Seguro que hay algo que ganar. (Voltaire)", source: "ConfiguroWeb"},
{quote:"Si dais la impresión de necesitar cualquier cosa, no os darán nada; para hacer fortuna, es preciso aparentar ser rico. (Alejandro Dumas)", source: "ConfiguroWeb"},
{quote:"Si despojas a los ricos, consigues empobrecerles; pero no consigues enriquecer a los pobres. (Máximo Gorki)", source: "ConfiguroWeb"},
{quote:"Si el dinero va por delante, todos los caminos están abiertos. (William Shakespeare)", source: "ConfiguroWeb"},
{quote:"Si puedes contar tu dinero, no eres un hombre verdaderamente rico. (Paul Getty)", source: "ConfiguroWeb"},
{quote:"Si queréis ser ricos, no aprendáis solamente a saber cómo se gana, sin también cómo se ahorra. (Benjamin Franklin)", source: "ConfiguroWeb"},
{quote:"Sin sobriedad nadie puede hacerse rico, y con ella muy pocos serán pobres. (Samuel Johnson)", source: "ConfiguroWeb"},
{quote:"Un tonto pobre siempre será un tonto. Un tonto rico será siempre rico. (Paul Lafitte)", source: "ConfiguroWeb"},
{quote:"Una gran fortuna es una gran servidumbre. (Séneca)", source: "ConfiguroWeb"}
]
console.log(quotes);

function getRandomQuote() {
  // this gets a random number ranging from 0 to (quotes.length - 1)
  var random = Math.floor(Math.random() * quotes.length);
  // the random number is used as the index for quotes to pick the right, random one and it is returned to the
  // print function.
  return(quotes[random ]);
}


function printQuote(){
  //Pull the quote in question from getRandomQuote
  var currentQuote = getRandomQuote();
  // Set a blank string to hold the HTML
  var html = ''
  //Set up a variable to point to our quote box in the HTML
  var quoteDiv = document.getElementById('quote-box')

  //Open up a p tag and place the quote itself in it
  html += '<p class="quote">' + currentQuote.quote 
  
  //If tags are present...
  if ('tags' in currentQuote){
    // ...Add the tags to the quote
      html += '  ' + currentQuote.tags.join(', ')
  }
  // Close the first p tag
  html += '</p>'

  // mandatory p tag for source
  html += '<p class="source">' + currentQuote.source 
  // if a citation is defined...
  if ('citation' in currentQuote) {
    // ...add it to the p tag
    html += '<span class="citation">' + currentQuote.citation + '</span>'
  }
  // If a year is defined...
  if ('year' in currentQuote){
    // ...add it to the p tag
    html += '<span class="year">' + currentQuote.year + '</span>'
  }
  html += '</p>'

  // take this HTML item we have been appending and set the html of the quote box to it
  quoteDiv.innerHTML = html

  // run the set randomBackground() program to change the background color
  setRandomBackground()
  
}

function setRandomBackground(){
  // This function changes the background color to one of 6 pre-defined colors based on a random
  // number generator.  First get the random number
  var randomNumber = Math.floor(Math.random() * 6)
  
  // then check to see what the number equals and assign the corresponding color
  if (randomNumber == 0){
    document.body.style.background = 'black';
  }else if (randomNumber == 1){
    document.body.style.background = 'blue';
  }else if (randomNumber == 2){
    document.body.style.background = 'green';
  }else if (randomNumber == 3){
    document.body.style.background = 'red';
  }else if (randomNumber == 4){
    document.body.style.background = 'purple';
  }else if (randomNumber == 5){
    document.body.style.background = 'yellow';
  }
}

// Run the function when the button is pressed...
document.getElementById('load-quote').addEventListener("click", printQuote, false);
// ...or when 30 seconds pass
window.setInterval(printQuote, 30000);